local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Common = ReplicatedStorage.Common

local Trails = require(Common.Trails.Trails)

local TrailsShop = {
    Trails.Red,
    Trails.Yellow,
    Trails.Blue,
    Trails.Green,
    Trails.Purple,
    Trails.Pink,
    Trails.White,
    Trails.Black,
    Trails.Hacker,
    Trails.Fire,
    Trails.Blossom,
    Trails.Frost,
    Trails.Electric,
    Trails.Rainbow,
    Trails.Banana,
}

return TrailsShop